// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DM.WR.Web.Reskin.Controllers
{
    public partial class CriteriaController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CriteriaController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetCriteria()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetCriteria);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult LoadCriteria()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.LoadCriteria);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult SaveCriteria()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SaveCriteria);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult UpdateCriteria()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.UpdateCriteria);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult DeleteCriteria()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DeleteCriteria);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CriteriaController Actions { get { return MVC.Criteria; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Criteria";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Criteria";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetCriteria = "GetCriteria";
            public readonly string LoadCriteria = "LoadCriteria";
            public readonly string SaveCriteria = "SaveCriteria";
            public readonly string UpdateCriteria = "UpdateCriteria";
            public readonly string DeleteCriteria = "DeleteCriteria";
            public readonly string DisplayDeleteCriteriaModal = "DisplayDeleteCriteriaModal";
            public readonly string DisplayUnsavedChangesModal = "DisplayUnsavedChangesModal";
            public readonly string DisplaySaveCriteriaModal = "DisplaySaveCriteriaModal";
            public readonly string DisplayRunInBackgroundModal = "DisplayRunInBackgroundModal";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetCriteria = "GetCriteria";
            public const string LoadCriteria = "LoadCriteria";
            public const string SaveCriteria = "SaveCriteria";
            public const string UpdateCriteria = "UpdateCriteria";
            public const string DeleteCriteria = "DeleteCriteria";
            public const string DisplayDeleteCriteriaModal = "DisplayDeleteCriteriaModal";
            public const string DisplayUnsavedChangesModal = "DisplayUnsavedChangesModal";
            public const string DisplaySaveCriteriaModal = "DisplaySaveCriteriaModal";
            public const string DisplayRunInBackgroundModal = "DisplayRunInBackgroundModal";
        }


        static readonly ActionParamsClass_GetCriteria s_params_GetCriteria = new ActionParamsClass_GetCriteria();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCriteria GetCriteriaParams { get { return s_params_GetCriteria; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCriteria
        {
            public readonly string assessmentCode = "assessmentCode";
            public readonly string displayType = "displayType";
        }
        static readonly ActionParamsClass_LoadCriteria s_params_LoadCriteria = new ActionParamsClass_LoadCriteria();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadCriteria LoadCriteriaParams { get { return s_params_LoadCriteria; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadCriteria
        {
            public readonly string criteriaId = "criteriaId";
            public readonly string enableEditMode = "enableEditMode";
            public readonly string criteriaName = "criteriaName";
            public readonly string criteriaDescription = "criteriaDescription";
            public readonly string criteriaDate = "criteriaDate";
        }
        static readonly ActionParamsClass_SaveCriteria s_params_SaveCriteria = new ActionParamsClass_SaveCriteria();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveCriteria SaveCriteriaParams { get { return s_params_SaveCriteria; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveCriteria
        {
            public readonly string name = "name";
            public readonly string summary = "summary";
        }
        static readonly ActionParamsClass_UpdateCriteria s_params_UpdateCriteria = new ActionParamsClass_UpdateCriteria();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateCriteria UpdateCriteriaParams { get { return s_params_UpdateCriteria; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateCriteria
        {
            public readonly string criteriaId = "criteriaId";
            public readonly string name = "name";
            public readonly string summary = "summary";
        }
        static readonly ActionParamsClass_DeleteCriteria s_params_DeleteCriteria = new ActionParamsClass_DeleteCriteria();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteCriteria DeleteCriteriaParams { get { return s_params_DeleteCriteria; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteCriteria
        {
            public readonly string criteriaId = "criteriaId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _CriteriaTable = "_CriteriaTable";
                public readonly string _DeleteCriteriaModal = "_DeleteCriteriaModal";
                public readonly string _RunInBackgroundModal = "_RunInBackgroundModal";
                public readonly string _SaveCriteriaModal = "_SaveCriteriaModal";
                public readonly string _UnsavedChangesModal = "_UnsavedChangesModal";
                public readonly string CriteriaPage = "CriteriaPage";
            }
            public readonly string _CriteriaTable = "~/Reskin/Views/Criteria/_CriteriaTable.cshtml";
            public readonly string _DeleteCriteriaModal = "~/Reskin/Views/Criteria/_DeleteCriteriaModal.cshtml";
            public readonly string _RunInBackgroundModal = "~/Reskin/Views/Criteria/_RunInBackgroundModal.cshtml";
            public readonly string _SaveCriteriaModal = "~/Reskin/Views/Criteria/_SaveCriteriaModal.cshtml";
            public readonly string _UnsavedChangesModal = "~/Reskin/Views/Criteria/_UnsavedChangesModal.cshtml";
            public readonly string CriteriaPage = "~/Reskin/Views/Criteria/CriteriaPage.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CriteriaController : DM.WR.Web.Reskin.Controllers.CriteriaController
    {
        public T4MVC_CriteriaController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetCriteriaOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string assessmentCode, string displayType);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetCriteria(string assessmentCode, string displayType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetCriteria);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "assessmentCode", assessmentCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "displayType", displayType);
            GetCriteriaOverride(callInfo, assessmentCode, displayType);
            return callInfo;
        }

        [NonAction]
        partial void LoadCriteriaOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int criteriaId, bool enableEditMode, string criteriaName, string criteriaDescription, string criteriaDate);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult LoadCriteria(int criteriaId, bool enableEditMode, string criteriaName, string criteriaDescription, string criteriaDate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.LoadCriteria);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "criteriaId", criteriaId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "enableEditMode", enableEditMode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "criteriaName", criteriaName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "criteriaDescription", criteriaDescription);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "criteriaDate", criteriaDate);
            LoadCriteriaOverride(callInfo, criteriaId, enableEditMode, criteriaName, criteriaDescription, criteriaDate);
            return callInfo;
        }

        [NonAction]
        partial void SaveCriteriaOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string name, string summary);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult SaveCriteria(string name, string summary)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SaveCriteria);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "summary", summary);
            SaveCriteriaOverride(callInfo, name, summary);
            return callInfo;
        }

        [NonAction]
        partial void UpdateCriteriaOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int criteriaId, string name, string summary);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult UpdateCriteria(int criteriaId, string name, string summary)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.UpdateCriteria);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "criteriaId", criteriaId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "summary", summary);
            UpdateCriteriaOverride(callInfo, criteriaId, name, summary);
            return callInfo;
        }

        [NonAction]
        partial void DeleteCriteriaOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int criteriaId);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DeleteCriteria(int criteriaId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DeleteCriteria);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "criteriaId", criteriaId);
            DeleteCriteriaOverride(callInfo, criteriaId);
            return callInfo;
        }

        [NonAction]
        partial void DisplayDeleteCriteriaModalOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DisplayDeleteCriteriaModal()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DisplayDeleteCriteriaModal);
            DisplayDeleteCriteriaModalOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DisplayUnsavedChangesModalOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DisplayUnsavedChangesModal()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DisplayUnsavedChangesModal);
            DisplayUnsavedChangesModalOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DisplaySaveCriteriaModalOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DisplaySaveCriteriaModal()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DisplaySaveCriteriaModal);
            DisplaySaveCriteriaModalOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DisplayRunInBackgroundModalOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DisplayRunInBackgroundModal()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DisplayRunInBackgroundModal);
            DisplayRunInBackgroundModalOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
