// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DM.WR.Web.Reskin.Controllers
{
    public partial class IowaFlexLongitudinalController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected IowaFlexLongitudinalController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.JsonResult> UpdateFilters()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateFilters);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.JsonResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult PersistLongitudinalFilters()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PersistLongitudinalFilters);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public IowaFlexLongitudinalController Actions { get { return MVC.IowaFlexLongitudinal; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "IowaFlexLongitudinal";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "IowaFlexLongitudinal";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetFilters = "GetFilters";
            public readonly string UpdateFilters = "UpdateFilters";
            public readonly string ResetFilters = "ResetFilters";
            public readonly string PersistLongitudinalFilters = "PersistLongitudinalFilters";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetFilters = "GetFilters";
            public const string UpdateFilters = "UpdateFilters";
            public const string ResetFilters = "ResetFilters";
            public const string PersistLongitudinalFilters = "PersistLongitudinalFilters";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string enableQueryLogging = "enableQueryLogging";
        }
        static readonly ActionParamsClass_UpdateFilters s_params_UpdateFilters = new ActionParamsClass_UpdateFilters();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateFilters UpdateFiltersParams { get { return s_params_UpdateFilters; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateFilters
        {
            public readonly string filterType = "filterType";
            public readonly string values = "values";
        }
        static readonly ActionParamsClass_PersistLongitudinalFilters s_params_PersistLongitudinalFilters = new ActionParamsClass_PersistLongitudinalFilters();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PersistLongitudinalFilters PersistLongitudinalFiltersParams { get { return s_params_PersistLongitudinalFilters; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PersistLongitudinalFilters
        {
            public readonly string persist = "persist";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _FiltersPanel = "_FiltersPanel";
                public readonly string IowaFlexLongitudinalPage = "IowaFlexLongitudinalPage";
            }
            public readonly string _FiltersPanel = "~/Reskin/Views/IowaFlexLongitudinal/_FiltersPanel.cshtml";
            public readonly string IowaFlexLongitudinalPage = "~/Reskin/Views/IowaFlexLongitudinal/IowaFlexLongitudinalPage.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_IowaFlexLongitudinalController : DM.WR.Web.Reskin.Controllers.IowaFlexLongitudinalController
    {
        public T4MVC_IowaFlexLongitudinalController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string enableQueryLogging);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(string enableQueryLogging)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "enableQueryLogging", enableQueryLogging);
            IndexOverride(callInfo, enableQueryLogging);
            return callInfo;
        }

        [NonAction]
        partial void GetFiltersOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetFilters()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetFilters);
            GetFiltersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UpdateFiltersOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string filterType, System.Collections.Generic.List<string> values);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.JsonResult> UpdateFilters(string filterType, System.Collections.Generic.List<string> values)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateFilters);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filterType", filterType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "values", values);
            UpdateFiltersOverride(callInfo, filterType, values);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.JsonResult);
        }

        [NonAction]
        partial void ResetFiltersOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult ResetFilters()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ResetFilters);
            ResetFiltersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PersistLongitudinalFiltersOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, bool persist);

        [NonAction]
        public override System.Web.Mvc.JsonResult PersistLongitudinalFilters(bool persist)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PersistLongitudinalFilters);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "persist", persist);
            PersistLongitudinalFiltersOverride(callInfo, persist);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
