// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DM.WR.Web.Reskin.Controllers
{
    public partial class ReportController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ReportController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult UpdateOptions()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.UpdateOptions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.PartialViewResult> SendReportToBackground()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SendReportToBackground);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.PartialViewResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetExcelReportString()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetExcelReportString);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetLastNameSearchString()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetLastNameSearchString);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult DownloadManager()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadManager);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetfileforDownload()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetfileforDownload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult DeletePDF()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DeletePDF);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReportController Actions { get { return MVC.Report; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Report";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Report";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetReportViewerData = "GetReportViewerData";
            public readonly string UpdateOptions = "UpdateOptions";
            public readonly string SendReportToBackground = "SendReportToBackground";
            public readonly string GetExcelReportString = "GetExcelReportString";
            public readonly string GetLastNameSearchString = "GetLastNameSearchString";
            public readonly string DownloadManager = "DownloadManager";
            public readonly string GetfileforDownload = "GetfileforDownload";
            public readonly string DeletePDF = "DeletePDF";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetReportViewerData = "GetReportViewerData";
            public const string UpdateOptions = "UpdateOptions";
            public const string SendReportToBackground = "SendReportToBackground";
            public const string GetExcelReportString = "GetExcelReportString";
            public const string GetLastNameSearchString = "GetLastNameSearchString";
            public const string DownloadManager = "DownloadManager";
            public const string GetfileforDownload = "GetfileforDownload";
            public const string DeletePDF = "DeletePDF";
        }


        static readonly ActionParamsClass_UpdateOptions s_params_UpdateOptions = new ActionParamsClass_UpdateOptions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateOptions UpdateOptionsParams { get { return s_params_UpdateOptions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateOptions
        {
            public readonly string parameters = "parameters";
        }
        static readonly ActionParamsClass_SendReportToBackground s_params_SendReportToBackground = new ActionParamsClass_SendReportToBackground();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendReportToBackground SendReportToBackgroundParams { get { return s_params_SendReportToBackground; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendReportToBackground
        {
            public readonly string name = "name";
        }
        static readonly ActionParamsClass_GetExcelReportString s_params_GetExcelReportString = new ActionParamsClass_GetExcelReportString();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetExcelReportString GetExcelReportStringParams { get { return s_params_GetExcelReportString; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetExcelReportString
        {
            public readonly string queryString = "queryString";
        }
        static readonly ActionParamsClass_GetLastNameSearchString s_params_GetLastNameSearchString = new ActionParamsClass_GetLastNameSearchString();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetLastNameSearchString GetLastNameSearchStringParams { get { return s_params_GetLastNameSearchString; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetLastNameSearchString
        {
            public readonly string lastName = "lastName";
        }
        static readonly ActionParamsClass_DownloadManager s_params_DownloadManager = new ActionParamsClass_DownloadManager();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadManager DownloadManagerParams { get { return s_params_DownloadManager; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadManager
        {
            public readonly string fileName = "fileName";
        }
        static readonly ActionParamsClass_GetfileforDownload s_params_GetfileforDownload = new ActionParamsClass_GetfileforDownload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetfileforDownload GetfileforDownloadParams { get { return s_params_GetfileforDownload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetfileforDownload
        {
            public readonly string Filename = "Filename";
            public readonly string FilePath = "FilePath";
            public readonly string UserID = "UserID";
            public readonly string FileID = "FileID";
            public readonly string reportType = "reportType";
        }
        static readonly ActionParamsClass_DeletePDF s_params_DeletePDF = new ActionParamsClass_DeletePDF();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeletePDF DeletePDFParams { get { return s_params_DeletePDF; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeletePDF
        {
            public readonly string FileID = "FileID";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ReportViewer = "_ReportViewer";
            }
            public readonly string _ReportViewer = "~/Reskin/Views/Report/_ReportViewer.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ReportController : DM.WR.Web.Reskin.Controllers.ReportController
    {
        public T4MVC_ReportController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GetReportViewerDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetReportViewerData()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetReportViewerData);
            GetReportViewerDataOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UpdateOptionsOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string parameters);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult UpdateOptions(string parameters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.UpdateOptions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parameters", parameters);
            UpdateOptionsOverride(callInfo, parameters);
            return callInfo;
        }

        [NonAction]
        partial void SendReportToBackgroundOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string name);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.PartialViewResult> SendReportToBackground(string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SendReportToBackground);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            SendReportToBackgroundOverride(callInfo, name);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.PartialViewResult);
        }

        [NonAction]
        partial void GetExcelReportStringOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string queryString);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetExcelReportString(string queryString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetExcelReportString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "queryString", queryString);
            GetExcelReportStringOverride(callInfo, queryString);
            return callInfo;
        }

        [NonAction]
        partial void GetLastNameSearchStringOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string lastName);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetLastNameSearchString(string lastName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetLastNameSearchString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastName", lastName);
            GetLastNameSearchStringOverride(callInfo, lastName);
            return callInfo;
        }

        [NonAction]
        partial void DownloadManagerOverride(T4MVC_System_Web_Mvc_FileResult callInfo, string fileName);

        [NonAction]
        public override System.Web.Mvc.FileResult DownloadManager(string fileName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadManager);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileName", fileName);
            DownloadManagerOverride(callInfo, fileName);
            return callInfo;
        }

        [NonAction]
        partial void GetfileforDownloadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string Filename, string FilePath, string UserID, int FileID, string reportType);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetfileforDownload(string Filename, string FilePath, string UserID, int FileID, string reportType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetfileforDownload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Filename", Filename);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FilePath", FilePath);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "UserID", UserID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FileID", FileID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reportType", reportType);
            GetfileforDownloadOverride(callInfo, Filename, FilePath, UserID, FileID, reportType);
            return callInfo;
        }

        [NonAction]
        partial void DeletePDFOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int FileID);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DeletePDF(int FileID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DeletePDF);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FileID", FileID);
            DeletePDFOverride(callInfo, FileID);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
