// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout_Pdf = "_Layout_Pdf";
                public readonly string EmptyPage = "EmptyPage";
            }
            public readonly string _Layout_Pdf = "~/Reskin/Views/Shared/_Layout_Pdf.cshtml";
            public readonly string EmptyPage = "~/Reskin/Views/Shared/EmptyPage.cshtml";
            static readonly _dm_uiClass s_dm_ui = new _dm_uiClass();
            public _dm_uiClass dm_ui { get { return s_dm_ui; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _dm_uiClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Alerts = "_Alerts";
                    public readonly string _Empty = "_Empty";
                    public readonly string _Footer = "_Footer";
                    public readonly string _Header = "_Header";
                    public readonly string _Layout_Base = "_Layout_Base";
                    public readonly string _Layout_Full = "_Layout_Full";
                    public readonly string _Layout_Login = "_Layout_Login";
                    public readonly string _Layout_NoMenu = "_Layout_NoMenu";
                    public readonly string _MagicFooter = "_MagicFooter";
                    public readonly string _MagicMainMenu = "_MagicMainMenu";
                    public readonly string _MagicMainMenuContainer = "_MagicMainMenuContainer";
                    public readonly string _MainMenu = "_MainMenu";
                    public readonly string _ModalLayout = "_ModalLayout";
                    public readonly string _404 = "404";
                }
                public readonly string _Alerts = "~/Reskin/Views/Shared/dm-ui/_Alerts.cshtml";
                public readonly string _Empty = "~/Reskin/Views/Shared/dm-ui/_Empty.cshtml";
                public readonly string _Footer = "~/Reskin/Views/Shared/dm-ui/_Footer.cshtml";
                public readonly string _Header = "~/Reskin/Views/Shared/dm-ui/_Header.cshtml";
                public readonly string _Layout_Base = "~/Reskin/Views/Shared/dm-ui/_Layout_Base.cshtml";
                public readonly string _Layout_Full = "~/Reskin/Views/Shared/dm-ui/_Layout_Full.cshtml";
                public readonly string _Layout_Login = "~/Reskin/Views/Shared/dm-ui/_Layout_Login.cshtml";
                public readonly string _Layout_NoMenu = "~/Reskin/Views/Shared/dm-ui/_Layout_NoMenu.cshtml";
                public readonly string _MagicFooter = "~/Reskin/Views/Shared/dm-ui/_MagicFooter.cshtml";
                public readonly string _MagicMainMenu = "~/Reskin/Views/Shared/dm-ui/_MagicMainMenu.cshtml";
                public readonly string _MagicMainMenuContainer = "~/Reskin/Views/Shared/dm-ui/_MagicMainMenuContainer.cshtml";
                public readonly string _MainMenu = "~/Reskin/Views/Shared/dm-ui/_MainMenu.cshtml";
                public readonly string _ModalLayout = "~/Reskin/Views/Shared/dm-ui/_ModalLayout.cshtml";
                public readonly string _404 = "~/Reskin/Views/Shared/dm-ui/404.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
